# Generated by Django 3.2 on 2021-06-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioBec', '0002_tipomedio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id_sansion', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_devolucion', models.DateField()),
            ],
            options={
                'db_table': 'sancion',
                'managed': False,
            },
        ),
    ]
