# Generated by Django 3.2 on 2021-06-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioBec', '0003_sancion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.IntegerField(primary_key=True, serialize=False)),
                ('editorial', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'editorial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado_ejem',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_ejem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado_pres',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_pres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado_res',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_res',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado_san',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_san',
                'managed': False,
            },
        ),
    ]
